### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by codler**

### CODE REVIEW

**Comment by christianalfoni** [comment]
Thanks, but now we have a new website 😄

**Comment by codler** [comment]
And what is that?

**Comment by christianalfoni** [comment]
It is same domain 😄 https://overmindjs.org

**Comment by codler** [comment]
I dont understand why this PR was rejected

**Comment by christianalfoni** [comment]
Oh, sorry @codler , I misread the diff!

But both `www` and root domain now works, so no worries 😄

**Pull request closed without merging**
