### PR TITLE
Fix overmind-graphql missing TS types

### PR DESCRIPTION
**Pull request by hipertracker**
Add missing TS types for overmind-graphql. 
It's for solving this error:
```
ERROR in node_modules/overmind-graphql/lib/index.d.ts(2,41):
TS7016: Could not find a declaration file for module 'phoenix'. 'node_modules/phoenix/priv/static/phoenix.js' implicitly has an 'any' type.
  Try `npm install @types/phoenix` if it exists or add a new declaration (.d.ts) file containing `declare module 'phoenix';`
Version: typescript 3.8.3, eslint 6.8.0
```

### CODE REVIEW

**Comment by henri-hulski** [comment]
I think `@types/*` should go into `devDependencies`.

**Comment by hipertracker** [comment]
Yes, of course. Should I create a new PR?

**Comment by henri-hulski** [comment]
You can overwrite this commit with
```
git commit --amend
git push --force
```

**Comment by hipertracker** [comment]
I did not pull nor fork the repo. I made the change and send PR directly in Github.

**Pull request merged**
