### PR TITLE
Svelte plugin

### PR DESCRIPTION
**Pull request by mfeitoza**
:)

### CODE REVIEW

**Comment by mfeitoza** [comment]
Just fixed one mistake I made in the first version.

**Comment by prestopasto** [comment]
Looks like the readme.md still says `overmind-vue`

**Comment by prestopasto** [comment]
@mfeitoza Awesome.  Do you know where this stands on getting merged in?

**Comment by christianalfoni** [comment]
This is really epic stuff @mfeitoza , thanks so much for creating it! I will bring it in now, will release tomorrow ;-) 

So sorry for bad follow up the last days, just been a bit overwhelming getting back into my open source flow 😄

**Pull request merged**
