### PR TITLE
Operators that track state mutations

### PR DESCRIPTION
**Pull request by luisherranz**
I've created a first draft for a `createMutationListenerOperator` but I'm not sure how to trigger a flush for the mutation in the test, or if I am missing something else.

Besides that, I have extended the operator callback to include the `track` function at the end. Maybe it's not the best way to expose it, suggestions are welcomed :)

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi @luisherranz and thanks for the suggestion!

I think your implementation looks really great, I am really impressed! 👍 😄 

Though I am not sure if this is the right approach. The reason is simply that we need a way to handle objects and arrays.  What I mean is that if you now do:

```js
waitForMutation(state => state.someArray)
```

Now this operator will not continue unless the whole array is replaced with a `set`. When you wait for mutations you probably want to look at any nested change of objects and arrays. 

So I was thinking about rather using `addFlushListener`, where we check if the returned value from the operator is a proxy. We can actually look at the paths of proxies doing `someValue[IS_PROXY] ? someValue[PATH] : null`. Then we can check the flushed paths if they match the path of the object. This allows any nested change to an array or object cause the `waitForMutation` to continue.

I really like your implementation here, as it works a lot like `Derived`, though it will not handle this scenario. 

You have any thoughts? :)

**Comment by luisherranz** [comment]
I've fixed the test and rebased the PR onto the current `next` branch. Probably not the best idea because some tests are failing.

> So I was thinking about rather using addFlushListener, where we check if the returned value from the operator is a proxy.

Ok, I'll take a look at this tomorrow 👍

**Comment by luisherranz** [comment]
There you go.

I've removed the `createMutationListenerOperator` and simply added the `context.execution` to the regular `createOperator`. I think it's much simpler and powerful that way. Now both the `waitForMutation` and `waitForFlush` operators can be created with the `createOperator`. Maybe the `mutate` operator as well. Take a look.

Let me know what you think. If you like this implementation we can go on with:
- Decide on a final name: `waitForMutation`? `waitForFlush`? Expose both?
- Create the built-in operator for that.
- Create the other `waitUntilTrue` operator and decide naming.
- Add more tests, including negative ones.

**Comment by christianalfoni** [comment]
HI there!

Yeah, this looks really interesting! I think we can avoid passing in execution explicitly as it should be part of the `context` itself. But adding those extra methods to get more "umph" looks like a good idea :)

One other thing. 

Do you expect the new operators to continuously trigger on mutation? For example:

```js
const someAction = pipe(
  waitMutation(state => state.foo),
  doSomething
)
```

Would you expect the first time `someAction` is called, it would always trigger "doSomething" any time "foo" changes? Or do you think of it like "wait"... so every time "someAction" is called it will wait until the mutation occurs and then continues? I am thinking the latter, where we have to make sure you dispose any subscriptions when it occurs :)

Let me find some time to do a run through the code trying your approach here, just to see if I discover something else. This is super helpful and thanks a bunch for contributing to getting this in :)

**Comment by luisherranz** [comment]
> I am thinking the latter, where we have to make sure you dispose any subscriptions when it occurs :)

I am thinking the latter too 👍 

> Let me find some time to do a run through the code trying your approach here, just to see if I discover something else.

I'm not sure if you can push changes to the PR without being a collaborator in my fork so I've added you there, just in case. Feel free to rebase the branch to the latest Overmind changes if you want :)

**Comment by christianalfoni** [comment]
Okay, so I have done an iteration here now.

1. Basically I am also passing in the execution on the context now to avoid an extra argument
2. Using `trackScope` instead of `track`, as it fits better
3. Disposing trees when they are evaluated
4. Removed flush test as I think flush might be confusing. `trackScope` will only trigger on a flush. So I think we should just stick with that initially at least

So yeah. I think we should just implement: `filterMutation` and `waitMutation`... the names just reflects existing operators so you kinda get a reference point.

About allowing "deep changes". We can later for example do `waitMutation(state => state.items, true)`, where `true` indicates that it should continue on any nested change.

But I think this looks great and think it is a really good start to get some more experience before we "flush it out" completely :)

**Comment by luisherranz** [comment]
> About allowing "deep changes". We can later for example do waitMutation(state => state.items, true), where true indicates that it should continue on any nested change.

Good idea 👍

**Comment by christianalfoni** [comment]
Cool! Working on a roadmap now which references this issue. Will get to adding those operators as soon as I can :)

**Comment by luisherranz** [comment]
Amazing Chris!

**Pull request merged**
