### PR TITLE
fix(overmind-svelte): add complete typing

### PR DESCRIPTION
**Pull request by abalmos**
Add types to `overmind-svelte` now that Svelte properly supports TypeScript.

This shouldn't change any logic, but @mfeitoza might want to review.

I hope this simple type change can make v26!

### CODE REVIEW

**Comment by mfeitoza** [comment]
Hi @abalmos, great! 
I working in a next version of svelte-overmind and already add support to types.

I will appreciate any feedback or tests, before push to overmind repo.
Basically now is using Proxifier, small change in api and types.
https://github.com/mfeitoza/overmind-svelte

**Comment by abalmos** [comment]
@mfeitoza Neat, looking forward to using it! Happy to drop it in on my project when ready, feel free to just ping me here.

@christianalfoni In the meantime, can we still merge this? I have a rather strict tsconfig.json and without these changes overmind-svelte is not usable.

**Comment by mfeitoza** [comment]
Currently I'm using the next version in one project.
I will do last check tomorrow and push it. I've been busy...

**Comment by abalmos** [comment]
@mfeitoza Great. If I get around to that project today I will spend some time using [this](https://github.com/mfeitoza/overmind-svelte/blob/master/src/overmindSvelte.ts) version and let you know. Otherwise, it might be Monday.

**Comment by mfeitoza** [comment]
@abalmos I already finish, but I'm having some issues with Jest and I'm trying to fix.

**Review by christianalfoni — APPROVED** [review]
Looks good to me 😄

**Comment by christianalfoni** [comment]
Or was there still something to be pushed here?

**Comment by abalmos** [comment]
Closing because I don't use Overmind anymore. This was unfinished and likely very out of date now anyway.

**Comment by mfeitoza** [comment]
I will update soon as possible.

**Pull request merged**
