### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced by **42%** 🎉

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /packages/overmind-website/src/images/overmind.png | 3.20kb | 0.76kb | 76.17% |
| /packages/overmind-website/src/images/js.png | 1.92kb | 0.51kb | 73.37% |
| /packages/overmind-website/images/devtool_count.png | 49.63kb | 24.13kb | 51.37% |
| /packages/overmind-website/images/todomvc_components.png | 104.57kb | 51.69kb | 50.57% |
| /packages/overmind-website/src/images/ts.png | 2.81kb | 1.42kb | 49.43% |
| /packages/overmind-website/images/devtool_disconnect.png | 84.89kb | 45.74kb | 46.12% |
| /packages/overmind-website/images/todomvc_actions.png | 129.50kb | 69.98kb | 45.96% |
| /packages/overmind-website/images/todomvc_history.png | 130.54kb | 70.63kb | 45.89% |
| /packages/overmind-website/images/front_devtool.png | 103.25kb | 58.41kb | 43.43% |
| /packages/overmind-website/images/todomvc_actions2.png | 162.75kb | 92.86kb | 42.94% |
| /packages/overmind-website/src/images/angular.png | 3.75kb | 2.14kb | 42.89% |
| /packages/overmind-website/images/devtool_change.png | 237.88kb | 137.37kb | 42.25% |
| /packages/overmind-website/images/state-ui.png | 13.78kb | 8.04kb | 41.62% |
| /packages/overmind-website/images/devtool_state.png | 169.33kb | 99.21kb | 41.41% |
| /packages/overmind-website/images/todomvc_state.png | 113.54kb | 66.65kb | 41.30% |
| /packages/overmind-website/images/devtool_effect.png | 247.56kb | 146.19kb | 40.95% |
| /packages/overmind-website/images/amazing_devtools.png | 188.28kb | 111.99kb | 40.52% |
| /packages/overmind-website/images/todomvc_state2.png | 116.32kb | 69.30kb | 40.43% |
| /packages/overmind-website/src/images/vue.png | 2.85kb | 1.77kb | 38.07% |
| /packages/overmind-website/images/statecharts.png | 61.66kb | 40.09kb | 34.98% |
| /packages/overmind-website/src/images/react.png | 4.80kb | 3.35kb | 30.24% |
| /logo.png | 55.94kb | 42.49kb | 24.03% |
| | | | |
| **Total :** | **1,988.75kb** | **1,144.73kb** | **42.44%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by MichaelDeBoey** [comment]
Ping @christianalfoni

**Comment by christianalfoni** [comment]
Hm.. could you try rebasing the PR?

**Comment by christianalfoni** [comment]
Ah, I will just merge

**Comment by MichaelDeBoey** [comment]
@christianalfoni if you add the bot to the organization/repo, it will create new PRs for optimizing all new images

**Pull request merged**
