### PR TITLE
Forward ref to connected component

### PR DESCRIPTION
**Pull request by veloek**
It should be possible to reference a connected component. As of now you'll only get a reference to the `HOC` wrapper if you try to add a `ref` (ignoring the TS error).

This PR is not complete with regards to typings nor testing, but it's been manually verified to work. I didn't want to invest too much time before I got some feedback. What do you think?

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi @veloek !

Sorry for late answer, but yeah, it makes sense to add `forwardRef` here for sure. I would encourage not using HOC, but for older codebases it is nice that we do support this 😄

**Comment by veloek** [comment]
@christianalfoni Cool, I'll go ahead and refine this PR then.

**Comment by veloek** [comment]
Made adjustments with regards to types and rebased on `next`. Please have another look, @christianalfoni 🙂

**Review by christianalfoni — APPROVED** [review]
Okay, lets try this 😄

**Pull request merged**
