### PR TITLE
simplify types

### PR DESCRIPTION
**Pull request by gaspard**
Simplify types. See #114

### CODE REVIEW

**Comment by christianalfoni** [comment]
Okay, just to explain previous commit.

1. I adjusted `Operation` to be a namespace you extend from instead, resulting in this typing:

```ts
type App = TApp<typeof config>

export type Action<Value = void, ReturnValue = Value> = TAction<
  App,
  Value,
  ReturnValue
>
export type Mutate<Value = any> = TOperation.Mutate<App, Value>
export type Map<Value, ReturnValue> = TOperation.Map<App, Value, ReturnValue>
export type Filter<Value = any> = TOperation.Filter<App, Value>
export type When<Value = any> = TOperation.When<App, Value>
export type Run<Value = any> = TOperation.Run<App, Value>
export type Fork<Value = any> = TOperation.Fork<App, Value>
export type Attempt<Value, ReturnValue> = TOperation.Attempt<
  App,
  Value,
  ReturnValue
>
export type Derive<Value> = TDerive<App, Value>
export type Reaction = TReaction<App>
```

Now there is no need to set up the context manually, this is done "under the hood". Also the operations will have their return values etc. also "under the hood".

2. To make override work there are a few things that needed to change:

1. Have to put the types in the `index.ts` file for it to be recognized as overrided
2. I changed the class name from `App` to `Overmind`, or else it would conflict
3. The `App` needs to be an interface as you can not replace types, only extend them
4. I had to put some `// @ts-ignore` due build errors when extend `BaseApp`, which would conflict with `TApp` extension in declare module

The really awesome thing here is that this "hack" has been simplified even more.

Currently I will keep this version in the docs, as all you have to do now is:

```ts
declare module 'overmind' {
  interface App extends TApp<typeof config> {}
}
```

While the other typing will get its space in the Typescript guide. This just makes it easier to get going and keeps the documentation clean. Super happy with this cleanup @gaspard, really great work! And we even got to keep "the hack" to make it less frightening to get going with Overmind :-)

**Comment by christianalfoni** [comment]
I am updating docs now, which should be the last need fixin`

**Comment by christianalfoni** [comment]
Okay, found a better way than `// @ts-ignore`

**Comment by gaspard** [comment]
@christianalfoni I think this is a good cleanup and clarification of the types and it will help working with overmind.

My only worry is that TS sees recursion in types because of this chain:

```ts
// Action --> depends on Context --> App --> config --> actions --> Action
```

The chain is broken by `Context` because it does not contain `actions`.
I hope TS sees that in some way.

**Comment by gaspard** [comment]
When I build the `context` I get this TS bug in `lib/index.d.ts`:

Any idea why this happens (tsc 2.9.2) ?

```ts
    createReactionFactory(prefix: string): {
        add(name: string, stateCb: (state: import("../../../../../../../../Users/gaspard/git/overmind/packages/node_modules/overmind/src/internalTypes").ResolveState<Config["state"] & {}>) => any, cb: Function): void;
        dispose(): void;
    };
```

**Comment by christianalfoni** [comment]
Hm, I see that interfaces can be circular, but types can not. Dunno, but maybe it would help using interfaces instead of types?

**Pull request merged**
